-- Listing reports and role-protected administration dashboard.
-- Apply once after hotfix-20260906-owner-favorites-autofeed.sql.

begin;

do $$
begin
  create type public.listing_report_reason as enum (
    'not_vehicle',
    'fraud',
    'wrong_information',
    'duplicate',
    'other'
  );
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.listing_report_status as enum (
    'open',
    'reviewed',
    'dismissed',
    'actioned'
  );
exception when duplicate_object then null;
end $$;

alter table public.listings
  add column if not exists admin_hidden boolean not null default false,
  add column if not exists admin_hidden_at timestamptz,
  add column if not exists admin_hidden_by uuid references public.profiles(id) on delete set null,
  add column if not exists admin_hidden_reason text;

create table if not exists public.listing_reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason public.listing_report_reason not null,
  details text,
  status public.listing_report_status not null default 'open',
  handled_by uuid references public.profiles(id) on delete set null,
  handled_at timestamptz,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (listing_id, reporter_id),
  check (details is null or length(trim(details)) between 3 and 1000),
  check (admin_note is null or length(trim(admin_note)) between 1 and 2000)
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (action in ('report_reviewed', 'report_dismissed', 'listing_hidden', 'listing_restored', 'admin_granted')),
  check (target_type in ('report', 'listing', 'profile'))
);

create index if not exists listing_reports_status_recent_idx
  on public.listing_reports (status, created_at desc);
create index if not exists listing_reports_listing_idx
  on public.listing_reports (listing_id, created_at desc);
create index if not exists profiles_created_at_idx
  on public.profiles (created_at desc);
create index if not exists listings_created_at_idx
  on public.listings (created_at desc);
create index if not exists messages_created_at_idx
  on public.messages (created_at desc);
create index if not exists favorites_created_at_idx
  on public.favorites (created_at desc);
create index if not exists admin_audit_recent_idx
  on public.admin_audit_log (created_at desc);

alter table public.listing_reports enable row level security;
alter table public.admin_audit_log enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.account_roles roles
    where roles.user_id = (select auth.uid())
      and roles.role = 'admin'
  );
$$;

create or replace function public.get_public_listing_detail(
  p_listing_id uuid
)
returns table (
  id uuid,
  title text,
  brand_name text,
  model_name text,
  city_name text,
  category text,
  price_kzt bigint,
  year integer,
  mileage_km integer,
  condition public.listing_condition,
  body_type text,
  gearbox text,
  origin_country text,
  engine_type text,
  steering text,
  drivetrain text,
  engine_volume numeric,
  color_name text,
  metallic boolean,
  cleared boolean,
  damaged boolean,
  has_vehicle_history boolean,
  description text,
  contact_phone_e164 text,
  seller_name text,
  published_at timestamptz,
  media jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select
    listing.id,
    listing.title,
    listing.brand_name,
    listing.model_name,
    listing.city_name,
    listing.category,
    listing.price_kzt,
    listing.year,
    listing.mileage_km,
    listing.condition,
    listing.body_type,
    listing.gearbox,
    listing.origin_country,
    listing.engine_type,
    listing.steering,
    listing.drivetrain,
    listing.engine_volume,
    listing.color_name,
    listing.metallic,
    listing.cleared,
    listing.damaged,
    listing.has_vehicle_history,
    listing.description,
    listing.contact_phone_e164,
    coalesce(nullif(trim(profile.display_name), ''), 'Частный продавец'),
    listing.published_at,
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', media.id,
          'kind', media.kind,
          'provider', media.provider,
          'object_key', media.object_key,
          'provider_asset_id', media.provider_asset_id,
          'poster_object_key', media.poster_object_key,
          'variants', media.variants,
          'sort_order', media.sort_order,
          'mime_type', media.mime_type,
          'width', media.width,
          'height', media.height,
          'duration_seconds', media.duration_seconds
        )
        order by
          case when media.kind = 'photo' then 0 else 1 end,
          media.sort_order,
          media.created_at
      )
      from public.listing_media media
      where media.listing_id = listing.id
        and media.status = 'ready'
        and media.deleted_at is null
    ), '[]'::jsonb)
  from public.listings listing
  left join public.profiles profile on profile.id = listing.owner_id
  where listing.id = p_listing_id
    and listing.deleted_at is null
    and (
      listing.status = 'active'
      or listing.owner_id = (select auth.uid())
      or public.is_admin()
    );
$$;

create or replace function public.submit_listing_report(
  p_listing_id uuid,
  p_reason public.listing_report_reason,
  p_details text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_report_id uuid;
  v_details text := nullif(trim(coalesce(p_details, '')), '');
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.listings listing
    where listing.id = p_listing_id
      and listing.status = 'active'
      and listing.deleted_at is null
      and listing.owner_id <> v_user_id
  ) then
    raise exception 'listing_not_reportable' using errcode = '22023';
  end if;

  if p_reason = 'other' and (v_details is null or length(v_details) < 10) then
    raise exception 'report_details_required' using errcode = '22023';
  end if;

  if v_details is not null and length(v_details) > 1000 then
    raise exception 'report_details_too_long' using errcode = '22023';
  end if;
  if v_details is not null and length(v_details) < 3 then
    raise exception 'report_details_too_short' using errcode = '22023';
  end if;

  if (
    select count(*)
    from public.listing_reports recent
    where recent.reporter_id = v_user_id
      and recent.created_at >= now() - interval '24 hours'
  ) >= 20 then
    raise exception 'report_rate_limit' using errcode = 'P0001';
  end if;

  insert into public.listing_reports (listing_id, reporter_id, reason, details)
  values (p_listing_id, v_user_id, p_reason, v_details)
  on conflict (listing_id, reporter_id) do nothing
  returning id into v_report_id;

  if v_report_id is null then
    select report.id into v_report_id
    from public.listing_reports report
    where report.listing_id = p_listing_id
      and report.reporter_id = v_user_id;
  end if;

  return v_report_id;
end;
$$;

create or replace function public.get_admin_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'registered_users', (select count(*) from public.profiles where deleted_at is null),
    'new_users_24h', (select count(*) from public.profiles where created_at >= now() - interval '24 hours' and deleted_at is null),
    'total_listings', (select count(*) from public.listings where deleted_at is null),
    'active_listings', (select count(*) from public.listings where status = 'active' and deleted_at is null),
    'draft_listings', (select count(*) from public.listings where status in ('draft', 'media_processing', 'pending_moderation') and deleted_at is null),
    'admin_hidden_listings', (select count(*) from public.listings where admin_hidden and deleted_at is null),
    'open_reports', (select count(*) from public.listing_reports where status = 'open'),
    'reports_24h', (select count(*) from public.listing_reports where created_at >= now() - interval '24 hours'),
    'events_24h', (select count(*) from public.behavior_events where occurred_at >= now() - interval '24 hours'),
    'active_visitors_24h', (
      select count(distinct coalesce(user_id::text, anonymous_id::text))
      from public.behavior_events
      where occurred_at >= now() - interval '24 hours'
    ),
    'messages_total', (select count(*) from public.messages where deleted_at is null),
    'favorites_total', (select count(*) from public.favorites)
  );
end;
$$;

create or replace function public.get_admin_activity(p_days integer default 14)
returns table (
  activity_date date,
  registrations bigint,
  listings_created bigint,
  reports_created bigint,
  behavior_events bigint,
  messages_sent bigint,
  favorites_added bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 14), 90));
begin
  if not public.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  return query
  select
    day_value::date,
    (select count(*) from public.profiles p where p.created_at >= day_value and p.created_at < day_value + interval '1 day'),
    (select count(*) from public.listings l where l.created_at >= day_value and l.created_at < day_value + interval '1 day'),
    (select count(*) from public.listing_reports r where r.created_at >= day_value and r.created_at < day_value + interval '1 day'),
    (select count(*) from public.behavior_events e where e.occurred_at >= day_value and e.occurred_at < day_value + interval '1 day'),
    (select count(*) from public.messages m where m.created_at >= day_value and m.created_at < day_value + interval '1 day' and m.deleted_at is null),
    (select count(*) from public.favorites f where f.created_at >= day_value and f.created_at < day_value + interval '1 day')
  from generate_series(
    current_date - (v_days - 1),
    current_date,
    interval '1 day'
  ) day_value
  order by day_value;
end;
$$;

create or replace function public.get_admin_reports(
  p_status text default 'open',
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id uuid,
  listing_id uuid,
  listing_title text,
  listing_status public.listing_status,
  listing_admin_hidden boolean,
  listing_cover_object_key text,
  reporter_id uuid,
  reporter_name text,
  reporter_phone text,
  reason public.listing_report_reason,
  details text,
  status public.listing_report_status,
  admin_note text,
  created_at timestamptz,
  handled_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  return query
  select
    report.id,
    report.listing_id,
    listing.title,
    listing.status,
    listing.admin_hidden,
    (
      select media.object_key
      from public.listing_media media
      where media.listing_id = listing.id
        and media.kind = 'photo'
        and media.status = 'ready'
        and media.deleted_at is null
      order by media.sort_order, media.created_at
      limit 1
    ),
    report.reporter_id,
    coalesce(nullif(trim(profile.display_name), ''), 'Пользователь QazAuto'),
    profile.phone_e164,
    report.reason,
    report.details,
    report.status,
    report.admin_note,
    report.created_at,
    report.handled_at
  from public.listing_reports report
  join public.listings listing on listing.id = report.listing_id
  join public.profiles profile on profile.id = report.reporter_id
  where coalesce(p_status, 'all') = 'all'
     or report.status::text = p_status
  order by
    case when report.status = 'open' then 0 else 1 end,
    report.created_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 100))
  offset greatest(coalesce(p_offset, 0), 0);
end;
$$;

create or replace function public.admin_review_listing_report(
  p_report_id uuid,
  p_status public.listing_report_status,
  p_admin_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := (select auth.uid());
  v_note text := nullif(trim(coalesce(p_admin_note, '')), '');
begin
  if not public.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  if p_status not in ('reviewed', 'dismissed', 'actioned') then
    raise exception 'invalid_report_status' using errcode = '22023';
  end if;
  if v_note is not null and length(v_note) > 2000 then
    raise exception 'admin_note_too_long' using errcode = '22023';
  end if;
  update public.listing_reports
  set status = p_status,
      handled_by = v_admin_id,
      handled_at = now(),
      admin_note = v_note,
      updated_at = now()
  where id = p_report_id;

  if not found then
    raise exception 'report_not_found' using errcode = 'P0002';
  end if;

  insert into public.admin_audit_log (actor_id, action, target_type, target_id, details)
  values (
    v_admin_id,
    case when p_status = 'dismissed' then 'report_dismissed' else 'report_reviewed' end,
    'report',
    p_report_id,
    jsonb_build_object('status', p_status, 'note', v_note)
  );
end;
$$;

create or replace function public.admin_set_listing_visibility(
  p_listing_id uuid,
  p_visible boolean,
  p_reason text default null,
  p_report_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := (select auth.uid());
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_is_hidden boolean;
begin
  if not public.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  select listing.admin_hidden into v_is_hidden
  from public.listings listing
  where listing.id = p_listing_id
    and listing.deleted_at is null;

  if not found then
    raise exception 'listing_not_found' using errcode = 'P0002';
  end if;

  if p_visible then
    if not v_is_hidden then
      raise exception 'listing_not_hidden_by_admin' using errcode = '22023';
    end if;

    update public.listings
    set status = 'active',
        admin_hidden = false,
        admin_hidden_at = null,
        admin_hidden_by = null,
        admin_hidden_reason = null,
        archived_at = null,
        rejection_reason = null,
        expires_at = now() + interval '30 days',
        version = version + 1,
        updated_at = now()
    where id = p_listing_id;
  else
    if v_reason is null or length(v_reason) < 3 then
      raise exception 'hide_reason_required' using errcode = '22023';
    end if;

    update public.listings
    set status = 'archived',
        admin_hidden = true,
        admin_hidden_at = now(),
        admin_hidden_by = v_admin_id,
        admin_hidden_reason = v_reason,
        archived_at = now(),
        rejection_reason = 'Скрыто администратором: ' || v_reason,
        version = version + 1,
        updated_at = now()
    where id = p_listing_id;

    if p_report_id is not null then
      update public.listing_reports
      set status = 'actioned',
          handled_by = v_admin_id,
          handled_at = now(),
          admin_note = v_reason,
          updated_at = now()
      where id = p_report_id
        and listing_id = p_listing_id;
    end if;
  end if;

  insert into public.admin_audit_log (actor_id, action, target_type, target_id, details)
  values (
    v_admin_id,
    case when p_visible then 'listing_restored' else 'listing_hidden' end,
    'listing',
    p_listing_id,
    jsonb_build_object('reason', v_reason, 'report_id', p_report_id)
  );
end;
$$;

create or replace function public.promote_admin_by_phone(p_phone_e164 text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  select profile.id into v_user_id
  from public.profiles profile
  where profile.phone_e164 = p_phone_e164
    and profile.phone_verified_at is not null
    and profile.deleted_at is null;

  if v_user_id is null then
    raise exception 'verified_profile_not_found' using errcode = 'P0002';
  end if;

  insert into public.account_roles (user_id, role)
  values (v_user_id, 'admin')
  on conflict do nothing;

  insert into public.admin_audit_log (actor_id, action, target_type, target_id, details)
  values (v_user_id, 'admin_granted', 'profile', v_user_id, jsonb_build_object('phone', p_phone_e164));

  return v_user_id;
end;
$$;

revoke all on table public.listing_reports from anon, authenticated;
revoke all on table public.admin_audit_log from anon, authenticated;
grant all on table public.listing_reports, public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

revoke all on function public.is_admin() from public, anon;
revoke all on function public.get_public_listing_detail(uuid) from public;
revoke all on function public.submit_listing_report(uuid, public.listing_report_reason, text) from public, anon;
revoke all on function public.get_admin_dashboard_stats() from public, anon;
revoke all on function public.get_admin_activity(integer) from public, anon;
revoke all on function public.get_admin_reports(text, integer, integer) from public, anon;
revoke all on function public.admin_review_listing_report(uuid, public.listing_report_status, text) from public, anon;
revoke all on function public.admin_set_listing_visibility(uuid, boolean, text, uuid) from public, anon;
revoke all on function public.promote_admin_by_phone(text) from public, anon, authenticated;

grant execute on function public.is_admin() to authenticated, service_role;
grant execute on function public.get_public_listing_detail(uuid) to anon, authenticated, service_role;
grant execute on function public.submit_listing_report(uuid, public.listing_report_reason, text) to authenticated, service_role;
grant execute on function public.get_admin_dashboard_stats() to authenticated, service_role;
grant execute on function public.get_admin_activity(integer) to authenticated, service_role;
grant execute on function public.get_admin_reports(text, integer, integer) to authenticated, service_role;
grant execute on function public.admin_review_listing_report(uuid, public.listing_report_status, text) to authenticated, service_role;
grant execute on function public.admin_set_listing_visibility(uuid, boolean, text, uuid) to authenticated, service_role;
grant execute on function public.promote_admin_by_phone(text) to service_role;

grant usage on type public.listing_report_reason, public.listing_report_status to authenticated, service_role;

commit;
