-- QazAuto marketplace schema v2.
-- Review this file before running it in Supabase. It expects a clean project.

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

do $$
begin
  create type public.account_status as enum ('active', 'blocked', 'deleted');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.app_role as enum ('user', 'moderator', 'admin');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.listing_condition as enum ('new', 'used');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.listing_status as enum (
    'draft',
    'media_processing',
    'pending_moderation',
    'active',
    'rejected',
    'sold',
    'expired',
    'archived',
    'deleted'
  );
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.media_kind as enum ('photo', 'video');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.media_status as enum (
    'pending_upload',
    'uploaded',
    'processing',
    'ready',
    'rejected',
    'deleted'
  );
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.moderation_decision as enum ('approved', 'rejected', 'changes_requested');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.behavior_event_type as enum (
    'impression',
    'open',
    'qualified_view',
    'active_view',
    'favorite',
    'unfavorite',
    'contact_reveal',
    'message_started',
    'hide',
    'search'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete restrict,
  display_name text,
  phone_e164 text,
  phone_verified_at timestamptz,
  city_name text,
  avatar_object_key text,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (display_name is null or length(trim(display_name)) between 2 and 80),
  check (phone_e164 is null or phone_e164 ~ '^[+][1-9][0-9]{7,14}$')
);

create unique index if not exists profiles_verified_phone_idx
  on public.profiles (phone_e164)
  where phone_e164 is not null and phone_verified_at is not null and deleted_at is null;

create table if not exists public.account_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.dealers (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references public.profiles(id) on delete restrict,
  legal_name text not null,
  display_name text not null,
  bin text,
  verification_status text not null default 'pending'
    check (verification_status in ('pending', 'verified', 'rejected', 'suspended')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_brands (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.vehicle_models (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.vehicle_brands(id) on delete restrict,
  slug text not null,
  name text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  unique (brand_id, slug),
  unique (brand_id, name)
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.locations(id) on delete restrict,
  kind text not null check (kind in ('country', 'region', 'city', 'district', 'settlement')),
  slug text not null unique,
  name_ru text not null,
  name_kk text,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete restrict,
  dealer_id uuid references public.dealers(id) on delete restrict,
  brand_id bigint references public.vehicle_brands(id) on delete restrict,
  model_id bigint references public.vehicle_models(id) on delete restrict,
  location_id bigint references public.locations(id) on delete restrict,
  title text not null,
  brand_name text not null,
  model_name text not null,
  city_name text not null,
  category text not null default 'cars',
  price_kzt bigint not null check (price_kzt between 1 and 10000000000),
  year integer not null check (year between 1900 and 2100),
  mileage_km integer not null default 0 check (mileage_km between 0 and 10000000),
  condition public.listing_condition not null default 'used',
  body_type text,
  gearbox text,
  origin_country text,
  engine_type text,
  steering text,
  drivetrain text,
  availability text not null default 'in_stock'
    check (availability in ('in_stock', 'on_order')),
  engine_volume numeric(3, 1) check (engine_volume is null or engine_volume between 0 and 20),
  color_name text,
  metallic boolean not null default false,
  can_finance boolean not null default false,
  finance_down_payment_kzt bigint
    check (finance_down_payment_kzt is null or finance_down_payment_kzt between 0 and 10000000000),
  finance_monthly_payment_kzt bigint
    check (finance_monthly_payment_kzt is null or finance_monthly_payment_kzt between 0 and 1000000000),
  cleared boolean not null default true,
  damaged boolean not null default false,
  has_vehicle_history boolean not null default false,
  description text,
  contact_phone_e164 text,
  status public.listing_status not null default 'draft',
  rejection_reason text,
  published_at timestamptz,
  expires_at timestamptz,
  sold_at timestamptz,
  archived_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  check (length(trim(title)) between 4 and 120),
  check (length(trim(brand_name)) between 1 and 80),
  check (length(trim(model_name)) between 1 and 120),
  check (length(trim(city_name)) between 1 and 120),
  check (description is null or length(description) <= 10000),
  check (contact_phone_e164 is null or contact_phone_e164 ~ '^[+][1-9][0-9]{7,14}$'),
  check (expires_at is null or published_at is not null)
);

create table if not exists public.listing_media (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  kind public.media_kind not null,
  provider text not null check (provider in ('cloudflare_r2', 'cloudflare_stream')),
  object_key text,
  provider_asset_id text,
  poster_object_key text,
  variants jsonb not null default '{}'::jsonb,
  status public.media_status not null default 'pending_upload',
  sort_order smallint not null default 0,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes between 1 and 524288000),
  width integer check (width is null or width between 1 and 20000),
  height integer check (height is null or height between 1 and 20000),
  duration_seconds numeric(6, 2)
    check (duration_seconds is null or duration_seconds between 0.1 and 60),
  checksum_sha256 text,
  perceptual_hash text,
  moderation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (
    (kind = 'photo' and provider = 'cloudflare_r2' and sort_order between 0 and 19)
    or
    (kind = 'video' and provider = 'cloudflare_stream' and sort_order = 0)
  ),
  check (object_key is not null or provider_asset_id is not null)
);

create unique index if not exists listing_media_photo_order_idx
  on public.listing_media (listing_id, sort_order)
  where kind = 'photo' and deleted_at is null;

create unique index if not exists listing_media_one_video_idx
  on public.listing_media (listing_id)
  where kind = 'video' and deleted_at is null;

create unique index if not exists listing_media_object_key_idx
  on public.listing_media (provider, object_key)
  where object_key is not null and deleted_at is null;

create table if not exists public.media_uploads (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  media_id uuid references public.listing_media(id) on delete cascade,
  object_key text not null unique,
  expected_mime_type text not null,
  max_size_bytes bigint not null,
  expires_at timestamptz not null,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_stats (
  listing_id uuid primary key references public.listings(id) on delete cascade,
  qualified_views bigint not null default 0,
  favorites_count bigint not null default 0,
  contact_reveals bigint not null default 0,
  quality_score numeric(8, 4) not null default 0,
  popularity_score numeric(8, 4) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table if not exists public.search_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  anonymous_id uuid,
  query_text text,
  filters jsonb not null default '{}'::jsonb,
  algorithm_version text not null default 'rules-v1',
  created_at timestamptz not null default now(),
  check (user_id is not null or anonymous_id is not null)
);

create table if not exists public.recommendation_impressions (
  id uuid primary key default gen_random_uuid(),
  search_session_id uuid not null references public.search_sessions(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  position integer not null check (position between 0 and 10000),
  rank_score numeric(12, 6),
  algorithm_version text not null,
  shown_at timestamptz not null default now(),
  unique (search_session_id, listing_id)
);

create table if not exists public.behavior_events (
  event_id uuid not null,
  occurred_at timestamptz not null default now(),
  received_at timestamptz not null default now(),
  event_type public.behavior_event_type not null,
  user_id uuid references public.profiles(id) on delete set null,
  anonymous_id uuid,
  session_id uuid not null,
  search_session_id uuid references public.search_sessions(id) on delete set null,
  listing_id uuid references public.listings(id) on delete set null,
  position integer check (position is null or position between 0 and 10000),
  active_milliseconds integer check (active_milliseconds is null or active_milliseconds between 0 and 3600000),
  metadata jsonb not null default '{}'::jsonb,
  primary key (event_id, occurred_at),
  check (user_id is not null or anonymous_id is not null)
) partition by range (occurred_at);

create or replace function public.ensure_behavior_events_partition(month_start date)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  partition_name text;
  partition_end date;
begin
  partition_name := 'behavior_events_' || to_char(month_start, 'YYYY_MM');
  partition_end := (month_start + interval '1 month')::date;

  execute format(
    'create table if not exists public.%I partition of public.behavior_events for values from (%L) to (%L)',
    partition_name,
    month_start,
    partition_end
  );
end;
$$;

select public.ensure_behavior_events_partition(date_trunc('month', current_date)::date);
select public.ensure_behavior_events_partition((date_trunc('month', current_date) + interval '1 month')::date);
create table if not exists public.behavior_events_default
  partition of public.behavior_events default;

create table if not exists public.listing_view_daily (
  listing_id uuid not null references public.listings(id) on delete cascade,
  viewer_key text not null,
  view_date date not null,
  user_id uuid references public.profiles(id) on delete set null,
  first_qualified_at timestamptz not null,
  last_seen_at timestamptz not null,
  active_milliseconds integer not null default 0,
  primary key (listing_id, viewer_key, view_date),
  check (length(viewer_key) between 32 and 128),
  check (active_milliseconds between 0 and 86400000)
);

create table if not exists public.user_preference_features (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  features jsonb not null default '{}'::jsonb,
  model_version text not null default 'rules-v1',
  computed_at timestamptz not null default now()
);

create table if not exists public.listing_rank_features (
  listing_id uuid primary key references public.listings(id) on delete cascade,
  features jsonb not null default '{}'::jsonb,
  model_version text not null default 'rules-v1',
  computed_at timestamptz not null default now()
);

create table if not exists public.moderation_reviews (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  moderator_id uuid not null references public.profiles(id) on delete restrict,
  decision public.moderation_decision not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_status_history (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  old_status public.listing_status,
  new_status public.listing_status not null,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

create table if not exists public.cookie_consents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  anonymous_id uuid,
  analytics_allowed boolean not null default false,
  personalization_allowed boolean not null default false,
  policy_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (user_id is not null or anonymous_id is not null)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_listing_public(p_listing_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.listings
    where id = p_listing_id
      and status = 'active'
      and deleted_at is null
  );
$$;

create or replace function public.owns_listing(p_listing_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.listings
    where id = p_listing_id
      and owner_id = (select auth.uid())
      and deleted_at is null
  );
$$;

create or replace function public.can_favorite_listing(p_listing_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.listings
    where id = p_listing_id
      and status = 'active'
      and deleted_at is null
      and owner_id <> (select auth.uid())
  );
$$;

create or replace function public.sync_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    display_name,
    phone_e164,
    phone_verified_at
  )
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.phone, ''),
    new.phone_confirmed_at
  )
  on conflict (id) do update
  set phone_e164 = excluded.phone_e164,
      phone_verified_at = excluded.phone_verified_at,
      updated_at = now();

  insert into public.account_roles (user_id, role)
  values (new.id, 'user')
  on conflict do nothing;

  return new;
end;
$$;

create or replace function public.create_listing_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.listing_stats (listing_id)
  values (new.id)
  on conflict do nothing;
  return new;
end;
$$;

create or replace function public.validate_listing_relationships()
returns trigger
language plpgsql
as $$
begin
  if new.dealer_id is not null and not exists (
    select 1
    from public.dealers
    where dealers.id = new.dealer_id
      and dealers.owner_id = new.owner_id
      and dealers.verification_status = 'verified'
  ) then
    raise exception 'Dealer does not belong to the listing owner or is not verified';
  end if;

  if new.model_id is not null and not exists (
    select 1
    from public.vehicle_models
    where vehicle_models.id = new.model_id
      and (new.brand_id is null or vehicle_models.brand_id = new.brand_id)
  ) then
    raise exception 'Vehicle model does not belong to the selected brand';
  end if;

  return new;
end;
$$;

create or replace function public.log_listing_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.listing_status_history (
      listing_id,
      old_status,
      new_status,
      changed_by
    )
    values (
      new.id,
      case when tg_op = 'INSERT' then null else old.status end,
      new.status,
      (select auth.uid())
    );
  end if;
  return new;
end;
$$;

create or replace function public.update_favorite_counter()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.listing_stats
    set favorites_count = favorites_count + 1,
        updated_at = now()
    where listing_id = new.listing_id;
    return new;
  end if;

  update public.listing_stats
  set favorites_count = greatest(favorites_count - 1, 0),
      updated_at = now()
  where listing_id = old.listing_id;
  return old;
end;
$$;

create or replace function public.submit_listing_for_moderation(
  p_listing_id uuid,
  p_owner_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.profiles
    where id = p_owner_id
      and status = 'active'
      and phone_verified_at is not null
      and deleted_at is null
  ) then
    raise exception 'A verified phone number is required';
  end if;

  if not exists (
    select 1
    from public.listings
    where id = p_listing_id
      and owner_id = p_owner_id
      and status in ('draft', 'rejected')
      and deleted_at is null
  ) then
    raise exception 'Listing cannot be submitted';
  end if;

  if not exists (
    select 1
    from public.listing_media
    where listing_id = p_listing_id
      and kind = 'photo'
      and status = 'ready'
      and deleted_at is null
  ) then
    raise exception 'At least one ready photo is required';
  end if;

  update public.listings
  set status = 'pending_moderation',
      rejection_reason = null,
      version = version + 1,
      updated_at = now()
  where id = p_listing_id;
end;
$$;

create or replace function public.moderate_listing(
  p_listing_id uuid,
  p_moderator_id uuid,
  p_decision public.moderation_decision,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.account_roles
    where user_id = p_moderator_id
      and role in ('moderator', 'admin')
  ) then
    raise exception 'Moderator role is required';
  end if;

  if not exists (
    select 1
    from public.listings
    where id = p_listing_id
      and status = 'pending_moderation'
      and deleted_at is null
  ) then
    raise exception 'Listing is not pending moderation';
  end if;

  insert into public.moderation_reviews (
    listing_id,
    moderator_id,
    decision,
    reason
  ) values (
    p_listing_id,
    p_moderator_id,
    p_decision,
    nullif(trim(p_reason), '')
  );

  if p_decision = 'approved' then
    update public.listings
    set status = 'active',
        rejection_reason = null,
        published_at = now(),
        expires_at = now() + interval '30 days',
        version = version + 1,
        updated_at = now()
    where id = p_listing_id;
  else
    update public.listings
    set status = 'rejected',
        rejection_reason = coalesce(nullif(trim(p_reason), ''), 'Changes required'),
        version = version + 1,
        updated_at = now()
    where id = p_listing_id;
  end if;
end;
$$;

create or replace function public.expire_listings()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  update public.listings
  set status = 'expired',
      updated_at = now()
  where status = 'active'
    and expires_at <= now();

  get diagnostics affected = row_count;
  return affected;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists dealers_set_updated_at on public.dealers;
create trigger dealers_set_updated_at
before update on public.dealers
for each row execute function public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

drop trigger if exists listing_media_set_updated_at on public.listing_media;
create trigger listing_media_set_updated_at
before update on public.listing_media
for each row execute function public.set_updated_at();

drop trigger if exists cookie_consents_set_updated_at on public.cookie_consents;
create trigger cookie_consents_set_updated_at
before update on public.cookie_consents
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_synced on auth.users;
create trigger on_auth_user_synced
after insert or update of phone, phone_confirmed_at, raw_user_meta_data on auth.users
for each row execute function public.sync_auth_user_profile();

drop trigger if exists listings_create_stats on public.listings;
create trigger listings_create_stats
after insert on public.listings
for each row execute function public.create_listing_stats();

drop trigger if exists listings_validate_relationships on public.listings;
create trigger listings_validate_relationships
before insert or update of owner_id, dealer_id, brand_id, model_id on public.listings
for each row execute function public.validate_listing_relationships();

drop trigger if exists listings_log_status on public.listings;
create trigger listings_log_status
after insert or update of status on public.listings
for each row execute function public.log_listing_status_change();

drop trigger if exists favorites_update_counter on public.favorites;
create trigger favorites_update_counter
after insert or delete on public.favorites
for each row execute function public.update_favorite_counter();

insert into public.profiles (id, display_name, phone_e164, phone_verified_at)
select
  id,
  nullif(raw_user_meta_data ->> 'full_name', ''),
  nullif(phone, ''),
  phone_confirmed_at
from auth.users
on conflict (id) do update
set phone_e164 = excluded.phone_e164,
    phone_verified_at = excluded.phone_verified_at;

insert into public.account_roles (user_id, role)
select id, 'user'
from auth.users
on conflict do nothing;

create index if not exists vehicle_models_brand_idx
  on public.vehicle_models (brand_id, sort_order, name);

create index if not exists locations_parent_idx
  on public.locations (parent_id, sort_order, name_ru);

create index if not exists listings_owner_created_idx
  on public.listings (owner_id, created_at desc)
  where deleted_at is null;

create index if not exists listings_active_recent_idx
  on public.listings (published_at desc, id)
  where status = 'active' and deleted_at is null;

create index if not exists listings_active_filters_idx
  on public.listings (category, location_id, brand_id, model_id, condition, year, price_kzt, id)
  where status = 'active' and deleted_at is null;

create index if not exists listings_active_text_idx
  on public.listings using gin (
    (brand_name || ' ' || model_name || ' ' || title) gin_trgm_ops
  )
  where status = 'active' and deleted_at is null;

create index if not exists listing_media_ready_idx
  on public.listing_media (listing_id, kind, sort_order)
  where status = 'ready' and deleted_at is null;

create index if not exists media_uploads_expiry_idx
  on public.media_uploads (expires_at)
  where completed_at is null;

create index if not exists favorites_listing_idx
  on public.favorites (listing_id, created_at desc);

create index if not exists search_sessions_user_idx
  on public.search_sessions (user_id, created_at desc)
  where user_id is not null;

create index if not exists search_sessions_anonymous_idx
  on public.search_sessions (anonymous_id, created_at desc)
  where anonymous_id is not null;

create index if not exists behavior_events_user_idx
  on public.behavior_events (user_id, occurred_at desc)
  where user_id is not null;

create index if not exists behavior_events_anonymous_idx
  on public.behavior_events (anonymous_id, occurred_at desc)
  where anonymous_id is not null;

create index if not exists behavior_events_listing_idx
  on public.behavior_events (listing_id, occurred_at desc)
  where listing_id is not null;

create index if not exists recommendation_impressions_listing_idx
  on public.recommendation_impressions (listing_id, shown_at desc);

create index if not exists listing_status_history_listing_idx
  on public.listing_status_history (listing_id, changed_at desc);

alter table public.profiles enable row level security;
alter table public.account_roles enable row level security;
alter table public.dealers enable row level security;
alter table public.vehicle_brands enable row level security;
alter table public.vehicle_models enable row level security;
alter table public.locations enable row level security;
alter table public.listings enable row level security;
alter table public.listing_media enable row level security;
alter table public.media_uploads enable row level security;
alter table public.listing_stats enable row level security;
alter table public.favorites enable row level security;
alter table public.search_sessions enable row level security;
alter table public.recommendation_impressions enable row level security;
alter table public.behavior_events enable row level security;
alter table public.listing_view_daily enable row level security;
alter table public.user_preference_features enable row level security;
alter table public.listing_rank_features enable row level security;
alter table public.moderation_reviews enable row level security;
alter table public.listing_status_history enable row level security;
alter table public.cookie_consents enable row level security;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "account_roles_select_own"
on public.account_roles for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "verified_dealers_public_read"
on public.dealers for select
to anon, authenticated
using (verification_status = 'verified' or (select auth.uid()) = owner_id);

create policy "vehicle_brands_public_read"
on public.vehicle_brands for select
to anon, authenticated
using (is_active);

create policy "vehicle_models_public_read"
on public.vehicle_models for select
to anon, authenticated
using (is_active);

create policy "locations_public_read"
on public.locations for select
to anon, authenticated
using (is_active);

create policy "active_listings_public_read"
on public.listings for select
to anon, authenticated
using (status = 'active' and deleted_at is null);

create policy "owners_read_own_listings"
on public.listings for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "active_media_public_read"
on public.listing_media for select
to anon, authenticated
using (
  status = 'ready'
  and deleted_at is null
  and public.is_listing_public(listing_id)
);

create policy "owners_read_own_media"
on public.listing_media for select
to authenticated
using (public.owns_listing(listing_id));

create policy "owners_read_uploads"
on public.media_uploads for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "active_listing_stats_public_read"
on public.listing_stats for select
to anon, authenticated
using (public.is_listing_public(listing_id));

create policy "owners_read_own_listing_stats"
on public.listing_stats for select
to authenticated
using (public.owns_listing(listing_id));

create policy "favorites_manage_own"
on public.favorites for all
to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and public.can_favorite_listing(listing_id)
);

create policy "preferences_read_own"
on public.user_preference_features for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "cookie_consents_manage_own"
on public.cookie_consents for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on all tables in schema public from anon, authenticated;

grant select on public.vehicle_brands, public.vehicle_models, public.locations
  to anon, authenticated;

grant select (id, display_name, city_name, avatar_object_key, status, created_at, updated_at)
  on public.profiles to authenticated;
grant update (display_name, city_name, avatar_object_key)
  on public.profiles to authenticated;
grant select on public.account_roles to authenticated;

grant select (id, display_name, verification_status, verified_at)
  on public.dealers to anon, authenticated;

grant select (
  id,
  brand_id,
  model_id,
  location_id,
  title,
  brand_name,
  model_name,
  city_name,
  category,
  price_kzt,
  year,
  mileage_km,
  condition,
  body_type,
  gearbox,
  origin_country,
  engine_type,
  steering,
  drivetrain,
  availability,
  engine_volume,
  color_name,
  metallic,
  can_finance,
  finance_down_payment_kzt,
  finance_monthly_payment_kzt,
  cleared,
  damaged,
  has_vehicle_history,
  description,
  status,
  published_at,
  expires_at,
  created_at,
  updated_at
) on public.listings to anon, authenticated;

grant select (
  id,
  listing_id,
  kind,
  provider,
  object_key,
  provider_asset_id,
  poster_object_key,
  variants,
  status,
  sort_order,
  width,
  height,
  duration_seconds,
  created_at
) on public.listing_media to anon, authenticated;

grant select (listing_id, qualified_views, favorites_count, updated_at)
  on public.listing_stats to anon, authenticated;

grant select, insert, delete on public.favorites to authenticated;
grant select on public.media_uploads to authenticated;
grant select on public.user_preference_features to authenticated;
grant select, insert, update on public.cookie_consents to authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

revoke all on function public.ensure_behavior_events_partition(date) from public, anon, authenticated;
revoke all on function public.is_listing_public(uuid) from public, anon, authenticated;
revoke all on function public.owns_listing(uuid) from public, anon, authenticated;
revoke all on function public.can_favorite_listing(uuid) from public, anon, authenticated;
revoke all on function public.submit_listing_for_moderation(uuid, uuid) from public, anon, authenticated;
revoke all on function public.moderate_listing(uuid, uuid, public.moderation_decision, text) from public, anon, authenticated;
revoke all on function public.expire_listings() from public, anon, authenticated;

grant execute on function public.ensure_behavior_events_partition(date) to service_role;
grant execute on function public.is_listing_public(uuid) to anon, authenticated, service_role;
grant execute on function public.owns_listing(uuid) to authenticated, service_role;
grant execute on function public.can_favorite_listing(uuid) to authenticated, service_role;
grant execute on function public.submit_listing_for_moderation(uuid, uuid) to service_role;
grant execute on function public.moderate_listing(uuid, uuid, public.moderation_decision, text) to service_role;
grant execute on function public.expire_listings() to service_role;
